service: authentication-api
frameworkVersion: '3'
plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  authentication:
    name: ${sls:stage}-authorizer-lbda
    description: Componente autenticador
    handler: dist/lambda.handler
    memorySize: 128
    timeout: 20
    events:
      - http:
          method: any
          path: /{proxy+}
